---
  name: Task - Publish Package to Pypi
  
  on:
    workflow_call:

  env: 
    PYTHON_VERSION: 3.12.4

  defaults: 
    run:
      working-directory: pragma-sdk

  jobs:
    pypi_publish:
      name: Upload package to PyPI
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: CfirTsabari/actions-pipx@v1
        - name: Install poetry
          run: pipx install poetry
        - uses: actions/setup-python@v5
          with:
            python-version: ${{ env.PYTHON_VERSION }}
            cache: "poetry"
        - run: pipx inject poetry poetry-monorepo-dependency-plugin
        - run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
        - run: poetry build -f sdist
        - run: poetry publish --skip-existing